package dev.engineeringlab.stratify.processor;

import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;

/**
 * Annotation processor for {@code @Provider} annotated classes.
 *
 * <p>This processor auto-generates META-INF/services files for classes annotated with
 * {@code @Provider}. It discovers all provider interfaces implemented by the annotated class and
 * registers them for ServiceLoader discovery.
 *
 * <h2>Example</h2>
 *
 * <pre>{@code
 * @Provider(name = "redis", priority = 10)
 * public class RedisMessageBroker implements MessageBrokerProvider {
 *     // ...
 * }
 * }</pre>
 *
 * <p>The processor automatically generates:
 *
 * <pre>
 * META-INF/services/com.example.MessageBrokerProvider
 * # Auto-generated by ProviderProcessor
 * com.example.redis.RedisMessageBroker
 * </pre>
 *
 * <h2>ServiceLoader Integration</h2>
 *
 * <p>At runtime, providers can be discovered using:
 *
 * <pre>{@code
 * ServiceLoader<MessageBrokerProvider> loader = ServiceLoader.load(MessageBrokerProvider.class);
 * for (MessageBrokerProvider provider : loader) {
 *     // Use provider
 * }
 * }</pre>
 *
 * @see AbstractProviderServiceProcessor
 * @see dev.engineeringlab.stratify.annotation.Provider
 * @since 1.0.0
 */
@SupportedAnnotationTypes("dev.engineeringlab.stratify.annotation.Provider")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public class ProviderProcessor extends AbstractProviderServiceProcessor {
  // All logic is in the base class
}
